services:
  kbqa_en:
    container_name: deeppavlov2023_kbqa_en
    restart: always
    build:
      args:
        PORT: 8008
        SRC_DIR: kbqa
      context: .
      dockerfile: kbqa/Dockerfile
    volumes:
      - "./kbqa:/src"
      - ~/.deeppavlov:/root/.deeppavlov
    ports:
      - 40196:8008
    environment:
      - CUDA_VISIBLE_DEVICES=7
      - LAN=EN
  kbqa_ru:
    container_name: deeppavlov2023_kbqa_ru
    restart: always
    build:
      args:
        PORT: 8008
        SRC_DIR: kbqa
      context: .
      dockerfile: kbqa/Dockerfile
    volumes:
      - "./kbqa:/src"
      - /home/aperevalov/deeppavlov-vol/2023:/root/.deeppavlov
    ports:
      - 40195:8008
    environment:
      - CUDA_VISIBLE_DEVICES=7
      - LAN=RU


version: '3.7'
